security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

            json_login:
                check_path: /api/login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            jwt: ~

        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /home   

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }

        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/events/new, roles: ROLE_ADMIN }
        - { path: ^/events/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/events/\d+/delete, roles: ROLE_ADMIN }