services:
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    ports:
      - "3307:3306"   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_reservation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  messenger-worker:
    image: php:8.3.30 
    container_name: symfony_worker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database
    command: php bin/console messenger:consume async -vv --limit=10
    restart: always

volumes:
  db_data: